Add Meilisearch example using a CLI
thedataquarry/rustinpieces pull request #49
Opened 2024-01-18 21:07 UTC by sanders41

2024-01-18 23:45 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +```json
```suggestion
```

2024-01-18 23:49 UTC, prrao87 reviewed
This is a very comprehensive piece, no doubt. Very useful. You did mention that CLIs are among the cases where Rust shows the biggest speedups over Python, so is there any way we could work that in here? I do something along those lines in the `mock_data` piece where the Rust version is significantly faster.

Even if we don't go down the road of running a full benchmark, it would be awesome to get some measure of how the Rust version is faster than the Python (if at all).

2024-01-18 23:49 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +```json
There's a rendering error because `null` isn't valid JSON for the syntax highlighter. I recommend leaving the `json` part out.

2024-01-18 23:57 UTC, sanders41 commented
> You did mention that CLIs are among the cases where Rust shows the biggest speedups over Python, so is there any way we could work that in here?

The biggest difference is in startup time and I have noticed that in these examples (unmeasured). There is a chance the Python example is faster on indexing. My perception while watching things run is it makes better use of async for this, but I haven't timed it yet or looked closely at the Rust SDK  code to verify. I'll see if I can come up with a good way to bench mark that includes the startup time, since I think that is the biggest win for the Rust CLI.

2024-01-19 00:04 UTC, sanders41 commented
On a quick test using `time meilisearch-cli create-index` seems to illustrate this well:

Rust: ./meilisearch-cli create-index  0.01s user 0.01s system 10% cpu 0.140 total
Python: meilisearch-cli create-index  0.59s user 0.05s system 82% cpu 0.777 total

2024-01-19 00:15 UTC, prrao87 commented
Awesome, I think it would be great to document the following in the readme:

1. Startup time (informal timing or just describing that Python is noticeably slower would work)
2. Indexing time (as you just noted)
3. Query time for 10 random queries
4. 

I think that should illustrate the goal of this piece really well!

2024-01-19 02:41 UTC, sanders41 commented
I added a performance section. For the searches instead of doing truly random I did the same 10 searches in both Rust and Python so things would be even. If you have a better ideal let me know, you tend to be better at coming up with good ideas for this kind of thing than I am.

2024-01-19 03:12 UTC, prrao87 requested changes
Excellent stuff! Just some typos to be fixed. But looks really good, I'd love to go in and reproduce the numbers on my end. I can add any other fixes if I find anything at that point, but this should be good to merge!

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +simlilar to tables in relational databases or collections in document databases.
```suggestion
similar to tables in relational databases or collections in document databases.
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +indexing, and preform searaches all through a CLI.
```suggestion
indexing, and perform searches all through a CLI.
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +Meilisearch is a fast, typo-tolerate search engine with a focus on being easy to setup and use. In
```suggestion
[Meilisearch](https://github.com/meilisearch/meilisearch) is a fast, open source, typo-tolerant search engine with a focus on being easy to setup and use. In
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +```
Missing the opening curly brace here.

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +match for multiple records. Because we want sort to take precidence we will update the ranking rules
```suggestion
match for multiple records. Because we want sort to take precedence we will update the ranking rules
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +has an optomization that sends documents for indexing concurrently when adding them in batches,
```suggestion
has an optimization that sends documents for indexing concurrently when adding them in batches,
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +because of the need to create an event loop. An exception to that in this case is `meilisearch-python-sdk`
```suggestion
because of the need to create an event loop. An exception in this case is that `meilisearch-python-sdk`
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +preforming the index creation and searches syncronously.
```suggestion
performing the index creation and searches synchronously.
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +the program syncronous `meilisearch-rust` using the [futures](https://github.com/rust-lang/futures-rs)
```suggestion
the program synchronous in `meilisearch-rust` using the [futures](https://github.com/rust-lang/futures-rs)
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +crate `block_on`, however it is not as simple to mix asyncio and syncronous calls as we have done in
```suggestion
crate `block_on`, however it is not as simple to mix asyncio and synchronous calls as we have done in
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +With Python there is overhead associated with starting the Python interperter which causes a noticable
```suggestion
With Python, there is overhead associated with starting the Python interpreter which causes a noticeable
```

2024-01-19 03:12 UTC, prrao87 commented on pieces/meilisearch_with_cli/README.md
> +example is significatnly faster than the Rust example at indexing, however almost all of this advantage
```suggestion
example is significantly faster than the Rust example at indexing, however almost all of this advantage
```

2024-01-19 03:15 UTC, prrao87 commented
The timing numbers are very interesting! I'm not sure I understand what causes the Python CLI to be that much slower for just 10 queries. This isn't like a running web server, so every query that gets sent to the CLI is like a cold start on a web server or database, right?

I suppose the scenario of us sending 10 queries in sequence is a bit contrived, as this isn't typically how people interact with a CLI. But based on your understanding of how users have used your CLIs in the past, the startup time for the Python interpreter is actually noticeable, I presume? Which makes sense that Rust is the go-to language for CLIs these days.

2024-01-19 03:16 UTC, prrao87 commented
> For the searches instead of doing truly random I did the same 10 searches (each unique) in both Rust and Python so things would be even. If you have a better ideal let me know, you tend to be better at coming up with good ideas for this kind of thing than I am.

I think the 10 unique searches is more than enough to illustrate the point here. Your example is better than any I'd have come up with in this case!

2024-01-19 12:08 UTC, sanders41 commented
> The timing numbers are very interesting! I'm not sure I understand what causes the Python CLI to be that much slower for just 10 queries. This isn't like a running web server, so every query that gets sent to the CLI is like a cold start on a web server or database, right?

Exactly. With each run Python interpreter has to startup first and load the program which takes some time. If the multiple searches were done with one CLI command I expect the numbers would be much closer. I expected to see a difference with this, but honestly I didn't think it would be this big. It tested a single search to try to confirm this big difference and the rust program ran in 0.010s while the Python took 0.737s. So you pay a big penalty for the startup and that adds up over runs.

> I suppose the scenario of us sending 10 queries in sequence is a bit contrived, as this isn't typically how people interact with a CLI. But based on your understanding of how users have used your CLIs in the past, the startup time for the Python interpreter is actually noticeable, I presume? Which makes sense that Rust is the go-to language for CLIs these days.

I initially was thinking it was contrived also and considered doing a different test. But the more I think about, it could add some value. It is true that you wouldn't do several rapid runs like this, but if you are taking the time to write a CLI it means you will most likely be running the program many times over the days/months/years. So over time the speed difference adds up. I'll add something to the description mentioning this.

2024-01-19 12:24 UTC, merged